import { useCallback, useEffect, useState } from 'react';
import { api, friendlyError } from '../services/api';
const KINDS=['FACULTY_INTERNSHIP','FDP','INDUSTRIAL_TRAINING','CONSULTANCY','RESEARCH_COLLABORATION'];
function useFetch(path){const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(Boolean(path));const refresh=useCallback(()=>{if(!path)return Promise.resolve();setLoading(true);setError('');return api.get(path).then(setData).catch(e=>setError(friendlyError(e))).finally(()=>setLoading(false));},[path]);useEffect(()=>{refresh();},[refresh]);return {data,error,loading,refresh};}
export function FacultyWorkspace(){
 const profile=useFetch('/faculty/profile'),posts=useFetch('/faculty/opportunities'),mine=useFetch('/faculty/applications/mine');
 const [form,setForm]=useState({title:'',description:'',kind:KINDS[0],organization:'',deadline:''}),[info,setInfo]=useState({institution:'',department:'',designation:'',interests:''}),[error,setError]=useState(''),[selected,setSelected]=useState(null),[applicants,setApplicants]=useState([]),[statement,setStatement]=useState('');
 useEffect(()=>{if(profile.data)setInfo(profile.data)},[profile.data]);
 async function run(action){try{await action();setError('');posts.refresh();mine.refresh();}catch(e){setError(friendlyError(e));}}
 async function show(id){try{setApplicants(await api.get(`/faculty/opportunities/${id}/applications`));setSelected(id);}catch(e){setError(friendlyError(e));}}
 return <section className="portal-page"><h2>Academician workspace</h2><p>Discover training and research collaboration, or post an opportunity.</p>{(error||profile.error||posts.error)&&<p role="alert" className="notice notice-error">{error||profile.error||posts.error}</p>}
 <div className="portal-grid"><form className="surface-card portal-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api.put('/faculty/profile',info);profile.refresh()})}}><h3>Faculty profile</h3>{Object.keys({institution:1,department:1,designation:1,interests:1}).map(k=><label key={k}>{k}<input required={k==='institution'} value={info[k]||''} onChange={e=>setInfo({...info,[k]:e.target.value})}/></label>)}<button className="button button-primary">Save profile</button></form>
 <form className="surface-card portal-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api.post('/faculty/opportunities',{...form,deadline:form.deadline||null});setForm({title:'',description:'',kind:KINDS[0],organization:'',deadline:''})})}}><h3>Create opportunity</h3><label>Type<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{KINDS.map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>)}</select></label>{['title','description','organization','deadline'].map(k=><label key={k}>{k}<input type={k==='deadline'?'date':'text'} required={k==='title'||k==='description'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button className="button button-primary">Publish</button></form></div>
 <h3>Opportunities</h3>{posts.data?.length===0&&<p>No opportunities yet.</p>}{(posts.data||[]).map(p=><article key={p.id} className="surface-card portal-card"><small>{p.kind.replaceAll('_',' ')} · {p.organization||'Academic network'}</small><h3>{p.title}</h3><p>{p.description}</p>{p.owner_id===profile.data?.user_id?<button onClick={()=>show(p.id)}>View applicants</button>:<form onSubmit={e=>{e.preventDefault();run(()=>api.post(`/faculty/opportunities/${p.id}/apply`,{statement}))}}><label>Interest statement<input required minLength="5" value={statement} onChange={e=>setStatement(e.target.value)}/></label><button disabled={mine.data?.some(a=>a.opportunity_id===p.id)}>Apply</button></form>}</article>)}
 {selected&&<div className="surface-card portal-card"><h3>Applicants</h3>{applicants.length===0?<p>None yet.</p>:applicants.map(a=><p key={a.id}>{a.applicant.full_name}: {a.statement} · {a.status} <button disabled={a.status==='SHORTLISTED'} onClick={()=>run(async()=>{await api.post(`/faculty/applications/${a.id}/shortlist`,{});show(selected)})}>Shortlist</button></p>)}</div>}
 <h3>My applications</h3>{(mine.data||[]).map(a=><p key={a.id}>{a.opportunity.title}: {a.status}</p>)}</section>;
}
function Bars({rows,label,value='count'}){return <div>{rows?.length?rows.map((r,i)=><div className="portal-chart-row" key={i}><span>{r.skill}</span><div><i style={{width:`${Math.max(2,Math.min(100,(r[value]/Math.max(...rows.map(x=>x[value]))) * 100))}%`}}/></div><strong>{r[value]}</strong></div>):<p>No data yet.</p>}</div>}
export function InstitutionWorkspace(){
 const analytics=useFetch('/institution/analytics');
 const outcomes=analytics.data?.application_outcomes||{};
 const outcomeStages=[['Applied','applied'],['Reviewing','reviewing'],['Shortlisted','shortlisted'],['Interview','interview'],['Offers','offer'],['Rejected','rejected']];
 return <section className="portal-page"><h2>Institution analytics</h2><p>Aggregate view for your institution.</p>{analytics.error&&<p role="alert">{analytics.error}</p>}{!analytics.data&&!analytics.error&&<p>Loading analytics…</p>}{analytics.data&&<><p>{analytics.data.institution}</p><div className="portal-metrics">{[['Students',analytics.data.student_count],['Placement readiness',`${analytics.data.placement_readiness}%`],['Internship applications',analytics.data.internship_applications],['Offers',outcomes.offer??0]].map(([k,v])=><article className="surface-card" key={k}><small>{k}</small><strong>{v}</strong></article>)}</div><article className="surface-card portal-card outcome-card"><h3>Application outcomes</h3><p>Progress for students at {analytics.data.institution}; this view contains aggregate counts only.</p><div className="outcome-stage-grid">{outcomeStages.map(([label,key])=><div className="outcome-stage" key={key}><small>{label}</small><strong>{outcomes[key]??0}</strong></div>)}</div></article><div className="portal-grid"><article className="surface-card portal-card"><h3>Common skill gaps</h3><Bars rows={analytics.data.common_skill_gaps}/></article><article className="surface-card portal-card"><h3>Industry skill demand</h3><Bars rows={analytics.data.skill_demand} value="weight"/></article><article className="surface-card portal-card"><h3>Average skill scores</h3><Bars rows={analytics.data.average_skill_scores} value="score"/></article></div></>}</section>;
}
export function SkillPassport(){
 const data=useFetch('/passport/me');const p=data.data;
 if(data.loading&&!p)return <section className="portal-page"><h2>Digital skill passport</h2><p>Loading your passport…</p></section>;
 if(data.error&&!p)return <section className="portal-page"><h2>Digital skill passport</h2><p role="alert" className="notice notice-error">{data.error}</p><button className="button button-secondary" onClick={data.refresh}>Try again</button></section>;
 if(!p)return <section className="portal-page"><h2>Digital skill passport</h2><p>Your passport is not available yet.</p></section>;
 const student=p.student||{}, skills=Array.isArray(p.skills)?p.skills:[], readiness=Array.isArray(p.role_readiness)?p.role_readiness:[], projects=Array.isArray(p.projects)?p.projects:[], certifications=Array.isArray(p.certifications)?p.certifications:[], experience=Array.isArray(p.experience)?p.experience:[], internships=Array.isArray(p.internships)?p.internships:[], assessments=Array.isArray(p.assessments)?p.assessments:[], opportunities=Array.isArray(p.opportunities)?p.opportunities:[];
 const Card=({title,children})=><article className="surface-card portal-card"><h3>{title}</h3>{children.length?children:<p className="muted-copy">Nothing to show yet.</p>}</article>;
 return <section className="portal-page"><h2>Digital skill passport</h2><p>Live information from your profile, assessments and matching engine.</p><div className="surface-card portal-card"><h3>{student.full_name||'Student'}</h3><p>{[student.degree,student.branch,student.institution].filter(Boolean).join(' · ')||'Add your education details to complete your passport.'}</p>{student.bio&&<p>{student.bio}</p>}</div><div className="portal-grid"><Card title="Skill scores">{skills.map((s,i)=><p key={s.skill_id??i}>{s.skill||'Skill'}: <strong>{s.overall_score??0}/100</strong> · Proficiency {s.proficiency_score??0} · Evidence {s.evidence_score??0}</p>)}</Card><Card title="Role readiness">{readiness.map((r,i)=><p key={r.role_id??i}>{r.role||'Role'}: <strong>{r.match_percentage??0}%</strong></p>)}</Card><Card title="Projects">{projects.map((x,i)=><p key={x.id??i}>{x.title||'Untitled project'}</p>)}</Card><Card title="Certifications">{certifications.map((x,i)=><p key={x.id??i}>{x.name||'Certification'}</p>)}</Card><Card title="Experience & internships">{[...experience.map(x=>x.job_title).filter(Boolean),...internships.map(x=>x.role).filter(Boolean)].map((x,i)=><p key={i}>{x}</p>)}</Card><Card title="Assessments">{assessments.map((x,i)=><p key={i}>{x.title||'Assessment'}: {x.score??0}%</p>)}</Card><Card title="Relevant opportunities">{opportunities.map((x,i)=><p key={x.opportunity?.id??i}>{x.opportunity?.title||'Opportunity'}: {x.match?.match_percentage??0}% match</p>)}</Card></div></section>;
}
