"""add_skill_evidence_table

Revision ID: 1f22e0d4f487
Revises: 3f423d0dfdbf
Create Date: 2026-09-27 20:35:18.295597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f22e0d4f487'
down_revision = '3f423d0dfdbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.Enum('PROJECT', 'CERTIFICATION', 'INTERNSHIP', 'EXPERIENCE', 'ASSESSMENT', 'COURSEWORK', 'OTHER', name='evidence_types', native_enum=False), nullable=False),
    sa.Column('evidence_title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('certification_id', sa.Integer(), nullable=True),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.Column('internship_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.Enum('SELF_REPORTED', 'VERIFIED', 'PENDING', name='verification_statuses', native_enum=False), nullable=False),
    sa.Column('evidence_strength', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_evidence_certification_id'), ['certification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_evidence_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_evidence_internship_id'), ['internship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_evidence_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_evidence_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_evidence_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_evidence_student_id'))
        batch_op.drop_index(batch_op.f('ix_skill_evidence_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_evidence_project_id'))
        batch_op.drop_index(batch_op.f('ix_skill_evidence_internship_id'))
        batch_op.drop_index(batch_op.f('ix_skill_evidence_experience_id'))
        batch_op.drop_index(batch_op.f('ix_skill_evidence_certification_id'))

    op.drop_table('skill_evidence')
    # ### end Alembic commands ###
