"""add_internship_table

Revision ID: 3f423d0dfdbf
Revises: 8f4e5b3c1cea
Create Date: 2026-09-27 20:30:47.539655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f423d0dfdbf'
down_revision = '8f4e5b3c1cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('internship_type', sa.Enum('SUMMER', 'WINTER', 'PART_TIME', 'FULL_TIME', 'REMOTE', 'OTHER', name='internship_types', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'ONGOING', 'PLANNED', 'CANCELLED', name='internship_statuses', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_internships_student_id'), ['student_id'], unique=False)

    op.create_table('internship_skills',
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('internship_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internship_skills')
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internships_student_id'))

    op.drop_table('internships')
    # ### end Alembic commands ###
