"""add_student_skill_table

Revision ID: 7b5d0e771b9b
Revises: 2cfe68f754c0
Create Date: 2026-09-27 19:58:40.603580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b5d0e771b9b'
down_revision = '2cfe68f754c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('proficiency', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiency_levels', native_enum=False), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('months_experience', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'skill_id', name='uq_student_skill')
    )
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_skills_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_skills_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_skills_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_skills_skill_id'))

    op.drop_table('student_skills')
    # ### end Alembic commands ###
