"""add_experience_table

Revision ID: 8f4e5b3c1cea
Revises: 38ad93fb8434
Create Date: 2026-09-27 20:17:43.192291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4e5b3c1cea'
down_revision = '38ad93fb8434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('employment_type', sa.Enum('INTERNSHIP', 'FULL_TIME', 'PART_TIME', 'FREELANCE', 'OTHER', name='employment_types', native_enum=False), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_student_id'), ['student_id'], unique=False)

    op.create_table('experience_skills',
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience_skills')
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_student_id'))

    op.drop_table('experiences')
    # ### end Alembic commands ###
